
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>ATC management</title>
        <link href="/css/main.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <header style="color:#FFFFFF;">
                <div id="header-content">
                       <?php
                       $this->headScript()->prependFile('/js/jquery-1.5.1.min.js');
                       //$this->headScript()->appendFile('/js/jquery.datePicker.js');
                       echo $this->headScript();
                       if(Zend_Auth::getInstance()->hasIdentity())
                        { ?>
                        <div  style="float:right;" class="login-logout">
                             <a href="/index/logout" style="text-decoration: none;text-align: left;">Logout</a>
                        </div>
                        <div id="main-menu" align="left" style="float:left;position: absolute;">
                                <a href="/home" style="">Home</a>
                                <a href="/center" style="">Centers</a>
                                <a href="/student" style="">Students</a>
                                <a href="/certificate" style="">Certificates</a>

                        </div>
                         <?php } ?>

                        <h1 style="font-size:40px;margin: 15px 0px;">ATC management </h1>
               </div>
         </header>
        <section>
                <?php echo $this->layout()->content; ?>
        </section>    
        <footer>
            <span>&copy; 2011 Company name Inc&trade;. All rights reserved</span>
        </footer>   
    </body>
</html>    