<head>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#error-status').hide(30000);
            $('#success-status').hide(30000);
        });
    </script>
</head>
<div id="addcenter-leftblock">
    <span>H</span>
</div>
<div class="center-details-form">
    <h2>Enter Details </h2>
    <span id="error-status" style="color: #D30E04;"><?php echo $this->status; ?></span>
    <span id="success-status" style="color: #68DD56;"><?php echo $this->success; ?></span>
<form method="POST">
<?php
      echo "<div class=form-elmts><label>ATC code      :</label> ".$this->form->atcCode ."</div>";
      echo "<div class=form-elmts><label>ATC Name      :</label> ".$this->form->atcName ."</div>";
      echo "<div class=form-elmts><label>Address       :</label> ".$this->form->atcAddress ."</div>";
      echo "<div class=form-elmts><label>District      :</label> ".$this->form->atcDistrict ."</div>";
      echo "<div class=form-elmts><label>State         :</label> ".$this->form->atcState ."</div>";
      echo "<div class=form-elmts><label>PIN code      :</label> ".$this->form->atcPincode ."</div>";
      echo "<div class=form-elmts><label>Category      :</label> ".$this->form->atcCategoryCode ."</div>";
?>
      <div class=form-elmts><label>Registration Date :</label>
      <?php echo $this->dateComboBox('reg');?></div>
      <?php echo "<div class=form-elmts style=\"float:right;\">".$this->form->submit ."</div>"; ?>
</form>
</div>