
<div class="details-form">
<h2>Enter Details </h2>
<?php
    //echo $this->form;
      echo "<div><label>ATC code      :</label> ".$this->form->atcCode ."</div>";
      echo "<label>ATC Name      :</label> ".$this->form->atcName . "<br \>";
      echo "<label>District      :</label> ".$this->form->atcDistrict . "<br \>";
      echo "<label>State         :</label> ".$this->form->atcState . "<br \>";
      echo "<label>PIN code      :</label> ".$this->form->atcPincode . "<br \>";
      echo "<label>Category code :</label> ".$this->form->atcCategoryCode . "<br \>";

      //echo $this->date();
?>


      <label>Registration Date :</label>
      <?php echo $this->dateComboBox('reg');?><br \>
      <label>Expiry Date :</label>
      <?php echo $this->dateComboBox('exp');?>
</div>