<head>
    <script type="text/javascript">
        $(document).ready(function(){
            /**
             *@description Determining the size of window
             */
            var windowWidth = document.documentElement.clientWidth;
	    var windowHeight = document.documentElement.clientHeight;
            /**
             *@Description Hide and show the Listcategory div
             */
            $('#list-category').hide();
            $('#backgroundPopup').hide();
            $('#list-category-button').click(function(){
                $("#backgroundPopup").height(windowHeight);
                $('#backgroundPopup').fadeIn('slow');
                $('#list-category').fadeIn('slow');
            })
            $('#list-category-close-button').click(function(){
                    $('#list-category').fadeOut('slow');
                    $('#backgroundPopup').fadeOut('slow');
            })
            /**
             *@Description Hide and show the Addcategory div
             */
            $('#add-category').hide();
            $('#add-category-button').click(function(){
                
	        $("#backgroundPopup").height(windowHeight);
                $('#backgroundPopup').fadeIn('slow');
                $('#add-category').fadeIn('slow');
            })
            $('#add-category-close-button').click(function(){
                    $('#add-category').fadeOut('slow');
                    $('#backgroundPopup').fadeOut('slow');
            })
            
            /**
             *@Description it will add category details
             *@param string $categoryname
             */
            $('#categoryAddButton').click(function(){
               var categoryName = $('#categoryName').val();
               if(categoryName==''){ alert('Name Field is Empty'); return(0); }
                     $.ajax({
                            type: "POST",
                            url: "/center/ajaxaddcategory",
                            data: "categoryName="+categoryName,
                            success: function(msg){
                              alert(msg);
                            }
                     });
             });      
        });
    </script>
</head>
<div id="view-content">
    <div class="center-menu">
        <a href="/center/addcenter"  title="Click here to add new center">Add a new center</a>
        <a href="#" id="add-category-button" title="Click here to add new category">Add a new category</a>
        <a href="#" id="list-category-button" title="Click here to view all categories">List Categories</a>&nbsp;
    </div>
    <div class="search-box">
        <form action="/center/search" method="POST">
            <label>Search Here :</label><?php echo $this->Searchcenter->searchCenterQueryBox; ?>
            <?php echo $this->Searchcenter->searchCenterOption; ?>
            <?php echo $this->Searchcenter->centerSearchsubmit; ?>
        </form>
    </div>
        <div id="backgroundPopup"></div>
        <div id="add-category">
            <div id="add-category-inner">
                <div id="add-category-close"><img src="/images/close_button.png" style="cursor: pointer;" width="12" id="add-category-close-button"  title="close"></div>
                <div style="color: #0279CE">
                    <h2>Add a new category</h2>
                </div>
                <div style="display: inline-block;">
                    <div id="add-category-formelements" style="padding: 10px 0; margin: 5px 0;display: inline-block;border-bottom: 1px solid #00AFF0;border-top: 1px solid #00AFF0; ">
                        <label>Category Name :</label>
                        <?php echo $this->addCategoryForm->categoryName; ?>
                    </div>
                    <div style="text-align: right;">
                        <?php echo $this->addCategoryForm->categoryAddButton; ?>
                    </div>
               </div>
            </div>
        </div>
        <div id="list-category">
            <div id="list-category-inner">
                <div id="list-category-close"><img src="/images/close_button.png" style="cursor: pointer;" width="12" id="list-category-close-button"  title="close"></div>
                <div id="list-category-content">
                    <div class="list-head" >
                        <div style="width: 65px;border : none;">Code</div>
                        <div style="width: 200px;border : none;">Name</div>
                    </div>
                    <?php
                          if($this->categoryDetails)
                          {
                              foreach ($this->categoryDetails AS $categoryDetail)
                              {
                                     echo "<div class=\"list-content\" >";
                                         echo "<div style=\"width: 65px;border : none\">".$categoryDetail['code'] . "</div>";
                                         echo "<div style=\"width: 200px;border : none\">".$categoryDetail['name'] . "</div>";
                                     echo "</div>";
                              }

                          }
                          else{
                               echo "There is no entry for centers";
                          }
                   ?>
                </div>
            </div>
        </div>
    <div class="center-list">
      <div class="list-head">
          <div style="width: 65px;">atccode</div>
          <div style="width: 100px;">Name</div>
          <div style="width: 180px;">Address</div>
          <div style="width: 100px;">district</div>
          <div style="width: 100px;">state</div>
          <div style="width: 65px;">pincode</div>
          <div style="width: 120px;">category</div>
          <div style="width: 120px;">Registration Date</div>
          <div style="width: 120px;">Contact Numbers</div>
      </div>
      
	  <?php
              if($this->centerDetails)
              {
                  foreach ($this->centerDetails AS $centerDetail)
                  {
                         echo "<div class=\"list-content\">";
                             echo "<div style=\"width: 65px;\">".$centerDetail['code'] . "</div>";
                             echo "<div style=\"width: 100px;\">".$centerDetail['name'] . "</div>";
                             echo "<div style=\"width: 180px;\">".$centerDetail['address'] . "</div>";
                             echo "<div style=\"width: 100px;\">".$centerDetail['district'] . "</div>";
                             echo "<div style=\"width: 100px;\">".$centerDetail['state'] . "</div>";
                             echo "<div style=\"width: 65px;\">".$centerDetail['pincode'] . "</div>";
                             echo "<div style=\"width: 120px;\">".$centerDetail['categoryname'] . "</div>";
                             echo "<div style=\"width: 120px;\">".$centerDetail['registration_date'] . "</div>";
                             echo "<div style=\"width: 120px;\">".$centerDetail['contact_number1'] . "</div>";
                         echo "</div>";
                  }
                      
              }
              else{
                   echo "There is no entry for centers";
              }
             
          ?>
       
    </div>
        <?php  echo "<div style=\"background-color : WHITE;float : right;\">" . $this->paginationControl($this->centerDetails, $this->paginationStyle, 'pagination_control.phtml') . "</div>"; ?>
</div>