<head>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#list-category').hide();
            $('#list-category-button').click(function(){
                $('#list-category').show('slow');
            })
            $('#list-category-close').click(function(){
                    $('#list-category').hide('slow');
                })
        });
    </script>
</head>
<div id="view-content">
    <div class="center-menu">
        <a href="/center/addcenter" title="Click here to add new center">Add a new center</a>
        <a href="#" title="Click here to edit center">Edit center</a>
        <a href="#" title="Click here to add new category">Add a new category</a>
        <a href="#" id="list-category-button" title="Click here to view all categories">List Categories</a>&nbsp;
        <label>Search Details :</label><input type="text" name="searchQuery" id="search-query">
        <select>
            <option value="1">ATC code</option>
            <option value="2">Center Name</option>
        </select>
        <input type="submit" name="searchSubmit" id="search-submit" value="Search">
    </div>
        <div id="list-category">
            <div id="list-category-close" title="close"><a href="#" >X</a></div>
            <div id="list-category-content">
                <div class="list-head">
                    <div style="width: 65px;">Code</div>
                    <div style="width: 200px;">Name</div>
                </div> 
                <?php
              if($this->categoryDetails)
              {
                  foreach ($this->categoryDetails AS $categoryDetail)
                  {
                         echo "<div class=\"list-content\">";
                             echo "<div style=\"width: 65px;\">".$categoryDetail['code'] . "</div>";
                             echo "<div style=\"width: 200px;\">".$categoryDetail['name'] . "</div>";
                         echo "</div>";
                  }
                      
              }
              else{
                   echo "There is no entry for centers";
              }
          ?>   
            </div>
         </div>    

    <br />
    <div class="center-list">
      <div class="list-head">
          <div style="width: 65px;">atccode</div>
          <div style="width: 100px;">Name</div>
          <div style="width: 180px;">Address</div>
          <div style="width: 100px;">district</div>
          <div style="width: 100px;">state</div>
          <div style="width: 65px;">pincode</div>
          <div style="width: 100px;">category</div>
          <div style="width: 120px;">Registration Date</div>
          <div style="width: 120px;">Contact Numbers</div>
      </div>
      
	  <?php
              if($this->centerDetails)
              {
                  foreach ($this->centerDetails AS $centerDetail)
                  {
                         echo "<div class=\"list-content\">";
                             echo "<div style=\"width: 65px;\">".$centerDetail['code'] . "</div>";
                             echo "<div style=\"width: 100px;\">".$centerDetail['name'] . "</div>";
                             echo "<div style=\"width: 180px;\">".$centerDetail['address'] . "</div>";
                             echo "<div style=\"width: 100px;\">".$centerDetail['district'] . "</div>";
                             echo "<div style=\"width: 100px;\">".$centerDetail['state'] . "</div>";
                             echo "<div style=\"width: 65px;\">".$centerDetail['pincode'] . "</div>";
                             echo "<div style=\"width: 100px;\">".$centerDetail['categoryname'] . "</div>";
                             echo "<div style=\"width: 120px;\">".$centerDetail['registration_date'] . "</div>";
                             echo "<div style=\"width: 120px;\">".$centerDetail['contact_number1'] . "</div>";
                         echo "</div>";
                  }
                      
              }
              else{
                   echo "There is no entry for centers";
              }
          ?>
       
    </div>
</div>