<div id="view-content">
    <a href="/center/addcenter">Add a new center</a>
    <br><br>
    <div style="">
        <b><span>atccode&nbsp;</span><span>district&nbsp;</span><span>state&nbsp;</span><span>pincode&nbsp;</span>
        <span>categoryname&nbsp;</span></b>
    </div>
    <br />
	<?php
            if($this->centerDetails)
            {
                foreach ($this->centerDetails AS $centerDetail)
                {
                       //echo $centerDetail['id'] . "&nbsp";
                       echo $centerDetail['atccode'] . "&nbsp;";
                       echo $centerDetail['district'] . "&nbsp;";
                       echo $centerDetail['state'] . "&nbsp;";
                       echo $centerDetail['pincode'] . "&nbsp;";
                       echo $centerDetail['categoryname'] . "&nbsp;";
                       echo "<br />";
                }
                      
            }
            else{
                 echo "There is no entry for centers";
            }
        ?>
</div>