<div id="view-content" style="padding: 25px 0 0 0; ">
    <div style="display: inline-block;padding: 4px 4px;background: rgba(0, 0, 0, 0.3);">
        <div style="display: inline-block;border: 1px #fff solid;padding: 4px 4px;background-color:#fff ">
         <!--   <div style="border-bottom: 1px #006BB7 solid;color: #006BB7;width: 300px;"><h2>Notifications</h2></div>
            <div style="display: inline-block;width: 400px;">
                <?php
//                    if($this->remainderDetails->toArray())
//                    {
//                        foreach ($this->remainderDetails AS $remainderDetail)
//                        {
//                             $date = new Zend_Date($remainderDetail->registration_date,'yyyy-MM-dd');
//                             //$date->add('1', Zend_Date::MONTH);
//                             $date->add('1', Zend_Date::YEAR);
//                             $expiryDate =  $date->toString('yyyy-MM-dd');
//                             echo "<div style=\"display:inline-block;color:RED;padding:5px 1px;\">Registration for the center <b>" . $remainderDetail->name . "</b> will expire on <b>" . $expiryDate . "</b></div>";
//                        }
//                    }
//                    else{
//                        echo "";
//                    }
                ?>
            </div> -->
         </div>
        
     </div><div style="text-align: center;"><h1>Page Under Construction</h1></div>
    <div style="display: inline-block;float: right;">
         
    </div>
</div>